### ISSUE TITLE
app首页mate-page会失效

### ISSUE THREAD

**Issue by 810505339** [uni-ku/root#2]
![image](https://github.com/user-attachments/assets/d9c5c38b-21a5-4578-9a29-d66a782ca928)
设置页面
![image](https://github.com/user-attachments/assets/d5dc7ce5-9375-40c9-9710-5ed61aad801f)
首页 

字体并没有变化

![image](https://github.com/user-attachments/assets/aad45cc9-a005-4cd5-ad24-464b77d08cf5)
这是其他页面

**Comment by Skiyee** [comment]
你好，具体流程是怎么样的？我目前无法理解图中需要实现什么？

**Comment by 810505339** [comment]
> 你好，具体流程是怎么样的？我目前无法理解图中需要实现什么？
![image](https://github.com/user-attachments/assets/e1f1e376-0e76-4e7f-8ae8-56ad5d4ca395)
在settingy页面修改了`<page-meta />` 然后首页不生效 其他页面可以生效
不知道是不是我使用了`@uni-helper/vite-plugin-uni-pages`文件路由的原因

**Comment by 810505339** [comment]
> 你好，在app中PageMeta 标签放在哪里？PageMeta 只能是页面内的第一个节点

![image](https://github.com/user-attachments/assets/11411d57-6a03-44ff-b740-2a2aa0937ab5)

在其他页面设置了`<page-meta v-bind="rootStyle" />` `rootStyle`然后首页不生效但是其他页面会生效
不确实是不是使用文件路由`import UniPages from '@uni-helper/vite-plugin-uni-pages'`这个的原因

**Comment by Skiyee** [comment]
可以看一下vite.config.* ?
需要确保 UniKuRoot 插件放置 UniPages 后面

**Comment by 810505339** [comment]
> 可以看一下vite.config.* ? 需要确保 UniKuRoot 插件放置 UniPages 后面

![image](https://github.com/user-attachments/assets/4519ee4e-0165-44e6-b6af-dfb186d34d7c)
mei没问题的~

**Comment by Skiyee** [comment]
没问题，我先复现看看

**Comment by Skiyee** [comment]
貌似未能复现该issue

https://github.com/user-attachments/assets/286b22a8-a5dc-47db-8a09-2970735974e8

代码：
![image](https://github.com/user-attachments/assets/caee9102-0bc6-4745-b975-aef957370b50)
![image](https://github.com/user-attachments/assets/720c2ada-0f35-41a9-9056-7fd707a12e7b)

其他两个页面的字体大小：`font-size: 1rem;`

**Comment by 810505339** [comment]
> 貌似未能复现该issue
> 
>  QQ2024814-114737.mp4 
> 代码： ![image](https://private-user-images.githubusercontent.com/120664167/357672387-caee9102-0bc6-4745-b975-aef957370b50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MDg3NDIsIm5iZiI6MTcyMzYwODQ0MiwicGF0aCI6Ii8xMjA2NjQxNjcvMzU3NjcyMzg3LWNhZWU5MTAyLTBiYzYtNDc0NS1iOTc1LWFlZjk1NzM3MGI1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwNDA3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWI0OTUxYmViNWVmZmE4ZmE4N2VjZTE5MmEyYjc5NzJjMWFkMmQ3ZGRmMzEyNmE5ODk3M2ZkMGJmODZjM2QyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f5fy3TPIpJlNBYLD79lhVvOmIzPEtLqycAsv5-YIqUA) ![image](https://private-user-images.githubusercontent.com/120664167/357672308-720c2ada-0f35-41a9-9056-7fd707a12e7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MDg3NDIsIm5iZiI6MTcyMzYwODQ0MiwicGF0aCI6Ii8xMjA2NjQxNjcvMzU3NjcyMzA4LTcyMGMyYWRhLTBmMzUtNDFhOS05MDU2LTdmZDcwN2ExMmU3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwNDA3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjljZWMxMWFmMzk4ZWVkMDQ0ZTM2ODEwNGZlYjg0Zjc3ZDE1ZDQzZjgyNmQ3Njk4N2E1ZWFjMzNhZDhjNDIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HYcb4Y2L3Gsi2npdqU1Zjq1i7-9ZmjIXTnEt4A4dFOE)
> 
> 其他两个页面的字体大小：`font-size: 1rem;`

在H5中没问题 但是使用hbx在app中会有问题

**Comment by 810505339** [comment]
> 貌似未能复现该issue
> 
>  QQ2024814-114737.mp4 
> 代码： ![image](https://private-user-images.githubusercontent.com/120664167/357672387-caee9102-0bc6-4745-b975-aef957370b50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MDg3NDIsIm5iZiI6MTcyMzYwODQ0MiwicGF0aCI6Ii8xMjA2NjQxNjcvMzU3NjcyMzg3LWNhZWU5MTAyLTBiYzYtNDc0NS1iOTc1LWFlZjk1NzM3MGI1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwNDA3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWI0OTUxYmViNWVmZmE4ZmE4N2VjZTE5MmEyYjc5NzJjMWFkMmQ3ZGRmMzEyNmE5ODk3M2ZkMGJmODZjM2QyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f5fy3TPIpJlNBYLD79lhVvOmIzPEtLqycAsv5-YIqUA) ![image](https://private-user-images.githubusercontent.com/120664167/357672308-720c2ada-0f35-41a9-9056-7fd707a12e7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MDg3NDIsIm5iZiI6MTcyMzYwODQ0MiwicGF0aCI6Ii8xMjA2NjQxNjcvMzU3NjcyMzA4LTcyMGMyYWRhLTBmMzUtNDFhOS05MDU2LTdmZDcwN2ExMmU3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwNDA3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjljZWMxMWFmMzk4ZWVkMDQ0ZTM2ODEwNGZlYjg0Zjc3ZDE1ZDQzZjgyNmQ3Njk4N2E1ZWFjMzNhZDhjNDIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HYcb4Y2L3Gsi2npdqU1Zjq1i7-9ZmjIXTnEt4A4dFOE)
> 
> 其他两个页面的字体大小：`font-size: 1rem;`

https://github.com/user-attachments/assets/aab8896e-bbe1-403c-a51b-e431b2f0c1ba

**Comment by Skiyee** [comment]
vite.config.* 里试着去掉 UniPages
HBX比较特殊，有些适配可能没跟上
