### ISSUE TITLE
当前页面怎么拿到全局组件实例

### ISSUE THREAD

**Issue by mmdlsu** [uni-ku/root#3]
使用defineExpose，当前页面无法拿到全局组件实例
![image](https://github.com/user-attachments/assets/a8c01eeb-293d-448b-9ee1-8ea56cd71d75)

**Comment by mmdlsu** [comment]
有没有办法通过getCurrentPages()拿到

**Comment by mmdlsu** [comment]
研究了好久，可以在js中调用uni.$modal.msg()这样，不知道有没有优雅的方案
![image](https://github.com/user-attachments/assets/8f573262-c890-44d8-a8ed-9065146ef005)
![image](https://github.com/user-attachments/assets/7173467c-68c3-49dd-a48b-30ad93ec6199)

**Comment by Skiyee** [comment]
谢谢反馈，通过 `getCurrentPages` 取到实例的功能，如果得空，我将增加该功能

**Comment by Skiyee** [comment]
> 研究了好久，可以在js中调用uni.$modal.msg()这样，不知道有没有优雅的方案 ![image](https://private-user-images.githubusercontent.com/57515771/358449775-8f573262-c890-44d8-a8ed-9065146ef005.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3Nzc1NTQsIm5iZiI6MTcyMzc3NzI1NCwicGF0aCI6Ii81NzUxNTc3MS8zNTg0NDk3NzUtOGY1NzMyNjItYzg5MC00NGQ4LWE4ZWQtOTA2NTE0NmVmMDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDAzMDA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwZmYyMGRlODQ2ZmQxZDBmNDZmNjAzYzlmZGJhMjRhODYzZDgyNzBlYjE5Y2M5M2E0YWI1MTFiMmMxMjdlODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wr2jbtp342YU2y1szfcqh16EkxJKaSNQe0j82IsyHCA) ![image](https://private-user-images.githubusercontent.com/57515771/358446403-7173467c-68c3-49dd-a48b-30ad93ec6199.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3Nzc1NTQsIm5iZiI6MTcyMzc3NzI1NCwicGF0aCI6Ii81NzUxNTc3MS8zNTg0NDY0MDMtNzE3MzQ2N2MtNjhjMy00OWRkLWE0OGItMzBhZDkzZWM2MTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDAzMDA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NjI4MWU0MGQzNjY2Y2MwODFkZmExYmQ5Mzg2ZDk1MDE3YzYyNTQyZTJlMDU1NTI1N2YxM2JhMGU5Nzc3NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lcCgrf7EvUeADTaj0AeOa25tRoNFfFJFRD6lelOiBUg)

由于 wot 的 toast 没提供相关调用 prop，所以至目前版本这种解决方法是可以的 😎

**Comment by Skiyee** [comment]
v0.3.0 released
