### ISSUE TITLE
刷新

### ISSUE THREAD

**Issue by boGuo97** [uni-ku/root#5]
![image](https://github.com/user-attachments/assets/dc9b3a87-d8ea-477b-8e44-99a35b5316a6)这个为什么还是会刷新页面

**Comment by boGuo97** [comment]
可能我没描述清除，我自定义的tabbar点击切换的时候这个组件会刷新，当前选中有问题

**Comment by Skiyee** [comment]
是正常的
需要配合 *组合式函数或状态管理库* 来保存点击状态
